"""
Citation verification for the Grounded Answer assistant.

This module verifies that citations generated by Gemini
actually refer to policy clauses supplied by the Policy Engine.
"""

import re


def extract_citations(text: str) -> list[str]:
    """
    Extract actual policy clause IDs from a generated answer.

    Examples:

        Source: §6.6.1 — Amendment No. 2026-01 §3.1

    should return:

        ["6.6.1"]

    The §3.1 part belongs to the amendment source name and
    should not be treated as a separate policy citation.
    """

    if not text:
        return []

    citations = []

    # ---------------------------------------------------------
    # 1. Look specifically for citations following "Source:"
    # ---------------------------------------------------------

    source_matches = re.findall(
        r"Source\s*:\s*§\s*([0-9]+(?:\.[0-9A-Za-z]+)+)",
        text,
        flags=re.IGNORECASE,
    )

    citations.extend(source_matches)

    # ---------------------------------------------------------
    # 2. If there is no "Source:" citation, look for explicit
    #    standalone clause references.
    #
    #    This supports answers such as:
    #
    #       According to §6.6.1, ...
    #
    # ---------------------------------------------------------

    if not citations:

        standalone_matches = re.findall(
            r"(?:according to|under|clause)\s+§\s*"
            r"([0-9]+(?:\.[0-9A-Za-z]+)+)",
            text,
            flags=re.IGNORECASE,
        )

        citations.extend(standalone_matches)

    # ---------------------------------------------------------
    # 3. Remove duplicates while preserving order
    # ---------------------------------------------------------

    seen = set()
    unique_citations = []

    for clause_id in citations:

        if clause_id not in seen:
            seen.add(clause_id)
            unique_citations.append(clause_id)

    return unique_citations


def verify_citations(
    answer: str,
    policy_evidence: list[dict],
) -> dict:
    """
    Verify that every clause cited by Gemini actually exists
    in the policy evidence supplied by the Policy Engine.
    """

    citations = extract_citations(answer)

    allowed_citations = {
        str(item["clause_id"])
        for item in policy_evidence
    }

    # ---------------------------------------------------------
    # No citation
    # ---------------------------------------------------------

    if not citations:

        return {
            "valid": False,
            "citations": [],
            "invalid_citations": [],
            "allowed_citations": sorted(allowed_citations),
            "reason": (
                "No policy citation was found in the answer."
            ),
        }

    # ---------------------------------------------------------
    # Check whether every citation is grounded
    # ---------------------------------------------------------

    invalid_citations = [
        citation
        for citation in citations
        if citation not in allowed_citations
    ]

    if invalid_citations:

        return {
            "valid": False,
            "citations": citations,
            "invalid_citations": invalid_citations,
            "allowed_citations": sorted(allowed_citations),
            "reason": (
                "The answer contains a citation that was not "
                "provided by the Policy Engine."
            ),
        }

    # ---------------------------------------------------------
    # All citations are valid
    # ---------------------------------------------------------

    return {
        "valid": True,
        "citations": citations,
        "invalid_citations": [],
        "allowed_citations": sorted(allowed_citations),
        "reason": (
            "All citations are grounded in the resolved policy."
        ),
    }